name: 'demo'
version: '1.0.0'
config-version: 2

profile: 'demo'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  demo:

    # allows GitHub Actions to override dataset for ANY dbt command
    +schema: "{{ env_var('DBT_DATASET_OVERRIDE', target.schema) }}"

    staging:
      +schema: staging
      +tags: ["staging"]

    dwh:
      +schema: dwh
      +tags: ["dwh"]

    marts:
      +schema: marts
      +tags: ["marts"]
