name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  demo:                          # matches: models/demo/*
    +schema: demo                # default for models directly under models/demo (if any)

    staging:                     # matches: models/demo/staging/*
      +schema: staging
      +tags: ["staging"]

    dwh:                         # matches: models/demo/dwh/*
      +schema: dwh
      +tags: ["dwh"]

    datamart:                    # matches: models/demo/datamart/*
      +schema: datamart
      +tags: ["datamart"]
