name: "demo"
version: "1.0.0"
#config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  staging:
    +schema: dwh
  # Base config for ALL models in the "demo" project namespace
  demo:
    +schema: dwh
