name: 'demo'
version: '1.0.0'
config-version: 2

profile: 'demo'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  demo:

    # Disable dbt's default “append folder to schema” behavior
    #+schema: null

    staging:
      +schema: staging
      +materialized: table

    dwh:
      +schema: dwh
      +materialized: table
