name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  demo:  # <-- dbt namespace for all models under models/demo/*
    # default schema if none overridden
    +schema: "demo"

    staging:
      +schema: "staging"
      +tags: ["staging"]

    dwh:
      +schema: "dwh"
      +tags: ["dwh"]

    datamart:
      +schema: "datamart"
      +tags: ["datamart"]
