name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  demo: {}     # project namespace - MUST exist

  staging:
    +schema: "staging"
    +tags: ["staging"]

  dwh:
    +schema: "dwh"
    +tags: ["dwh"]

  marts:
    +schema: "datamart"
    +tags: ["marts"]
