name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  demo:

    # Global override so GitHub Actions can control the dataset if needed
    +schema: "{{ env_var('DBT_DATASET_OVERRIDE', target.schema) }}"

    # ---------------------
    # Models under: models/staging/*
    # ---------------------
    staging:
      +schema: "staging"
      +materialized: table
      +tags: ["staging"]

    # ---------------------
    # Models under: models/dwh/*
    # ---------------------
    dwh:
      +schema: "dwh"
      +materialized: table
      +tags: ["dwh"]

    # ---------------------
    # Models under: models/marts/*
    # ---------------------
    marts:
      +schema: "marts"
      +materialized: table
      +tags: ["marts"]
