name: demo

version: 1.0.0

profile: bigquery

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_modules"]

models:
  demo:
    +materialized: table
    
    staging:
      +schema: staging

    sources:
      +schema: raw
