name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  demo: {}     # your project namespace — MUST be here, but EMPTY

  # ---------------------------
  # Folder → Schema mapping
  # ---------------------------

  staging:
    +schema: "staging"
    +materialized: table

  dwh:
    +schema: "dwh"
    +materialized: table

  marts:
    +schema: "marts"
    +materialized: table
