name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  demo:
    +materialized: table

  # ================================
  # FOLDER → SCHEMA MAPPING
  # ================================
  staging:
    +schema: "staging"

  dwh:
    +schema: "dwh"

  marts:
    +schema: "marts"
