name: "demo"
project-name: "demo"   # <-- IMPORTANT: forces dbt to use the correct project name in CI/CD
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  demo:                   # <-- must match project-name above

    # Global override (optional)
    # Allows switching schema via environment variable: DBT_DATASET_OVERRIDE
    +schema: "{{ env_var('DBT_DATASET_OVERRIDE', target.schema) }}"

    # -----------------------------
    # STAGING MODELS
    # -----------------------------
    staging:
      +schema: "staging"
      +tags: ["staging"]

    # -----------------------------
    # DWH MODELS
    # -----------------------------
    dwh:
      +schema: "dwh"
      +tags: ["dwh"]

    # -----------------------------
    # MARTS MODELS (optional)
    # If folder doesn’t exist yet, dbt just warns; no error
    # -----------------------------
    marts:
      +schema: "marts"
      +tags: ["marts"]
