name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  #demo:
  #  +schema: "{{ env_var('DBT_DATASET_OVERRIDE', '') }}"
    staging:
      +schema: "staging"
      +tags: ["staging"]

    dwh:
      +schema: "dwh"
      +tags: ["dwh"]

    datamart:
      +schema: "datamart"
      +tags: ["datamart"]
