name: "demo"
version: "1.0.0"
#config-version: 2

profile: "demo"

model-paths: ["models"]

models:

  # Base config for ALL models in the "demo" project namespace
  demo:
    #+schema: demo

  # Folder: models/demo/staging
    staging:
      #+schema: staging
      #+tags: ["staging"]

  # Folder: models/demo/dwh
    dwh:
      +dataset: dwh
   # +tags: ["dwh"]

  # Folder: models/demo/datamart
  #demo.datamart:
   # +schema: datamart
   # +tags: ["datamart"]
