name: "demo"
version: "1.0.0"
config-version: 2

profile: "demo"

model-paths: ["models"]

models:
  # This applies to ALL models, but overridden below
  demo:
    +materialized: table

# -------------------------------------
# FOLDER → SCHEMA MAPPING (CORRECTED)
# These keys MUST match folder names
# -------------------------------------
  staging:
    +schema: "staging"

  dwh:
    +schema: "dwh"

  marts:
    +schema: "marts"
